_BASE_: "fiber_rcnn_r50_fpn.yaml"

MODEL:
  BACKBONE:
    FREEZE_AT: 1
  ANCHOR_GENERATOR:
    SIZES: [[16], [32], [64], [128], [256]]
    ASPECT_RATIOS: [[0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0]]
  RPN:
    PRE_NMS_TOPK_TRAIN: 6000
    PRE_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 3000
    POST_NMS_TOPK_TEST: 1500
    NMS_THRESH: 0.9
    BATCH_SIZE_PER_IMAGE: 512
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 768
    POSITIVE_FRACTION: 0.33
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.4

INPUT:
  MIN_SIZE_TRAIN: [896, 960, 1024]
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 960
  MAX_SIZE_TEST: 1600

SOLVER:
  BASE_LR: 0.0002
  MAX_ITER: 5000
  STEPS: (3500, 4400)
  WARMUP_ITERS: 300
  IMS_PER_BATCH: 1

TEST:
  EVAL_PERIOD: 250

OUTPUT_DIR: "./output/fiberrcnn_r50_fpn_thin_fiber"
